sigm/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from principal.views import *

urlpatterns = [
    path('estaciones/adicionar/', estacion_add_view, name='estacion_add_view'),
    path('estaciones/modificar/<int:estacion_id>/', estacion_modify_view, name='estacion_modify_view'),
    path('estaciones/modificar/<int:estacion_id>/eliminar/', estacion_delete_view, name='estacion_delete_view'),
    path('rvm/adicionar/', rvm_add_view, name='rvm_add_view'),
    path('rvm/modificar/<int:rvm_id>/', rvm_modify_view, name='rvm_modify_view'),
    path('rvm/modificar/<int:rvm_id>/eliminar/', rvm_delete_view, name='rvm_delete_view'),
    path('iovmg/adicionar/', iovmg_add_view, name='iovmg_add_view'),
    path('iovmg/modificar/<int:iovmg_id>/', iovmg_modify_view, name='iovmg_modify_view'),
    path('iovmg/modificar/<int:iovmg_id>/eliminar/', iovmg_delete_view, name='iovmg_delete_view'),
    path('iovmp/adicionar/', iovmp_add_view, name='iovmp_add_view'),
    path('iovmp/modificar/<int:iovmp_id>/', iovmp_modify_view, name='iovmp_modify_view'),
    path('iovmp/modificar/<int:iovmp_id>/eliminar/', iovmp_delete_view, name='iovmp_delete_view'),
    path('pmp/adicionar/', pmp_add_view, name='pmp_add_view'),
    path('pmp/modificar/<int:pmp_id>/', pmp_modify_view, name='pmp_modify_view'),
    path('pmp/modificar/<int:pmp_id>/eliminar/', pmp_delete_view, name='pmp_delete_view'),
    path('pmg/adicionar/', pmg_add_view, name='pmg_add_view'),
    path('pmg/modificar/<int:pmg_id>/', pmg_modify_view, name='pmg_modify_view'),
    path('pmg/modificar/<int:pmg_id>/eliminar/', pmg_delete_view, name='pmg_delete_view'),
    path("login/", login_request, name="login"),
    path("logout/", cerrar_sesion, name="cerrar_sesion"),
    path("inicio/", admin_index, name="admin_index"),
    path('admin/', admin.site.urls),
    path('divulgacion/', index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

principal/models.py
from django.db import models


# Create your models here.
#la clase estacion y todas las clases del models.py heredan de models.Model
class Estacion(models.Model):
    #esta clase tiene un campo estacion que es de tipo texto (CharField), tinee una longitud
    #maxima de 255 chars y sera llamado Nombre
    estacion = models.CharField(max_length=255, verbose_name='Nombre')

    #str es una funcion que define la representacion del objeto como cadena de texto
    def __str__(self):
        return self.estacion

    #clase que define los metadatos referencia singular y plural de cada instancia
    class Meta:
        verbose_name = 'Estación'
        verbose_name_plural = '01 - Estaciones'

class ReporteVariableMeteorologica(models.Model):
    #foreignkey es una relacion de uno a muchos en este caso con la tabla estacion
    #cuando se borre la estacion correspondiente, este campo se que vacio
    #null = True y blank = True indican que este campo puede ser vacio y/o nulo
    estacion = models.ForeignKey(Estacion, on_delete=models.SET_NULL, null=True, blank=True)
    meteorologo = models.CharField(max_length=255, verbose_name='Meteorólogo')
    #campo de fecha y hora
    fecha_hora = models.DateTimeField(verbose_name='Fecha y hora')
    #FloatField indica un campo de tipo decimal
    dirr = models.FloatField(verbose_name='DIRR')
    dirs = models.FloatField(verbose_name='DIRS')
    vels = models.FloatField(verbose_name='VELS')
    velp = models.FloatField(verbose_name='VELP')
    temperatura = models.FloatField()
    # IntegerField indica un campo de tipo entero
    humedad = models.IntegerField()
    presion = models.IntegerField()

    def __str__(self):
        return self.meteorologo

    class Meta:
        verbose_name = 'Reporte de variable meteorológica'
        verbose_name_plural = '02 - Reportes de variables meteorólogicas'


class InformeOficialVariableMeteorologicaPronvincial(models.Model):
    #lista con tuplas (valor, provincia)
    #el valor izquierdo indica qué se guardara en la base de datos y el valor derecho lo que se mostrara
    #en la interfaz de usuario
    PROVINCIA_CHOICES = (
        ('1','Pinar del Río'),
        ('2', 'La Habana'),
        ('3', 'Artemisa'),
        ('4', 'Mayabeque'),
        ('5', 'Matanzas'),
        ('6', 'Villa Clara'),
        ('7', 'Cienfuegos'),
        ('8', 'Sancti Spíritus'),
        ('9', 'Ciego de Avila'),
        ('10', 'Camaguey'),
        ('11', 'Las Tunas'),
        ('12', 'Holguín'),
        ('13', 'Granma'),
        ('14', 'Santiago de Cuba'),
        ('15', 'Guantánamo'),
        ('16', 'Isla de la Juventud'),
    )
    estacion = models.ForeignKey(Estacion, on_delete=models.SET_NULL, null=True, blank=True)
    #el atributo choises indica cuales seran los elementos del combobox
    provincia = models.CharField(max_length=255, choices=PROVINCIA_CHOICES)
    tecnico = models.CharField(max_length=255, verbose_name='Técnico')
    temperatura = models.FloatField()
    viento = models.FloatField()
    lluvia = models.FloatField()
    humedad = models.IntegerField()
    barometro = models.IntegerField()
    fecha_hora = models.DateTimeField(verbose_name='Fecha y hora')

    def __str__(self):
        return self.tecnico

    class Meta:
        verbose_name = 'Informe oficial de variable meteorológica provincial'
        verbose_name_plural = '03 - Informes oficiales de variables meteorólogicas provinciales'

class InformeVariableMeteorologicaGeneral(models.Model):
    tecnico = models.CharField(max_length=255, verbose_name='Técnico')
    temperatura = models.FloatField()
    viento = models.FloatField()
    lluvia = models.FloatField()
    humedad = models.IntegerField()
    barometro = models.IntegerField()
    fecha_hora = models.DateTimeField(verbose_name='Fecha y hora')

    def __str__(self):
        return self.tecnico

    class Meta:
        verbose_name = 'Informe de variable meteorológica general'
        verbose_name_plural = '04 - Informes de variables meteorólogicas generales'

class ParteMeteorologicoProvincial(models.Model):
    PROVINCIA_CHOICES = (
        ('1', 'Pinar del Río'),
        ('2', 'La Habana'),
        ('3', 'Artemisa'),
        ('4', 'Mayabeque'),
        ('5', 'Matanzas'),
        ('6', 'Villa Clara'),
        ('7', 'Cienfuegos'),
        ('8', 'Sancti Spíritus'),
        ('9', 'Ciego de Avila'),
        ('10', 'Camaguey'),
        ('11', 'Las Tunas'),
        ('12', 'Holguín'),
        ('13', 'Granma'),
        ('14', 'Santiago de Cuba'),
        ('15', 'Guantánamo'),
        ('16', 'Isla de la Juventud'),
    )
    meteorologo = models.CharField(max_length=255, verbose_name='Meteorólogo')
    provincia = models.CharField(max_length=255, choices=PROVINCIA_CHOICES)
    temperatura = models.FloatField()
    viento = models.FloatField()
    lluvia = models.FloatField()
    fecha_hora = models.DateTimeField(verbose_name='Fecha y hora')

    def __str__(self):
        return self.meteorologo

    class Meta:
        verbose_name = 'Parte meteorológico provincial'
        verbose_name_plural = '05 - Partes meteorológicos provinciales'


class ParteMeteorologicoGeneral(models.Model):
    tecnico = models.CharField(max_length=255, verbose_name='Técnico')
    temperatura = models.FloatField()
    viento = models.FloatField()
    lluvia = models.FloatField()
    fecha_hora = models.DateTimeField(verbose_name='Fecha y hora')

    def __str__(self):
        return self.tecnico

    class Meta:
        verbose_name = 'Parte meteorológico general'
        verbose_name_plural = '06 - Partes meteorológicos generales'

templates/add_template.html
{% extends "base.html" %}
{% block contenido %}
    <nav class="gtco-nav" role="navigation" style="background-color: black">
        <div class="container">
            <div class="row">
                <div class="col-sm-2 col-xs-12">
                    <div id="gtco-logo"><a href="{% url 'admin_index' %}">Partes<em>Meteorologicos</em></a></div>
                </div>
                <div class="col-xs-10 text-right menu-1 main-nav">
                    <span>Insertar </span>
                    <ul>
                        {% if 'principal.add_estacion' in request.user.get_all_permissions %}
                            <li style="cursor: pointer"><a onclick="window.location.replace('/estaciones/adicionar/')">Estaciones</a>
                            </li>
                        {% endif %}
                        {% if 'principal.add_reportevariablemeteorologica' in request.user.get_all_permissions %}
                            <li style="cursor: pointer"><a onclick="window.location.replace('/rvm/adicionar/')">RVM</a></li>
                        {% endif %}
                        {% if 'principal.add_informevariablemeteorologicageneral' in request.user.get_all_permissions %}
                            <li style="cursor: pointer"><a onclick="window.location.replace('/iovmg/adicionar/')">IOVMG</a>
                            </li>
                        {% endif %}
                        {% if 'principal.add_informeoficialvariablemeteorologicapronvincial' in request.user.get_all_permissions %}
                            <li style="cursor: pointer"><a onclick="window.location.replace('/iovmp/adicionar/')">IOVMP</a>
                            </li>
                        {% endif %}
                        {% if 'principal.add_partemeteorologicoprovincial' in request.user.get_all_permissions %}
                            <li style="cursor: pointer"><a onclick="window.location.replace('/pmp/adicionar/')">PMP</a>
                        {% endif %}
                        {% if 'principal.add_partemeteorologicogeneral' in request.user.get_all_permissions %}
                            <li style="cursor: pointer"><a onclick="window.location.replace('/pmg/adicionar/')">PMG</a>
                        {% endif %}
                    </ul>
                </div>
                Bienvenido {{ usuario }}<br>
                <a href="{% url 'cerrar_sesion' %}">Cerrar sesion</a><br>
                <a href="{% url 'index' %}">Ver listado de partes meteorológicos</a><br>
            </div>

        </div>
    </nav>
    <section id="gtco-about" data-section="about" style="padding: 10em 0">
        <div class="container">
            <div class="row row-pb-md">
                <div class="col-md-8 heading animate-box" data-animate-effect="fadeIn">
                    {% load crispy_forms_tags %}

                    <!--Login-->
                    <div class="container py-5">
                        <h1>Adicionar una {{ objeto }}</h1>
                        <form method="POST">
                            {% csrf_token %}
                            {{ form.as_ul }}
                            <button class="btn btn-primary" type="submit">Adicionar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>


{% endblock %}

templates/admin_index.html
{% extends "base.html" %}
{% block contenido %}

    <nav class="gtco-nav" role="navigation" style="background-color: black">
        <div class="container">
            <div class="row">
                <div class="col-sm-2 col-xs-12">
                    <div id="gtco-logo"><a href="{% url 'admin_index' %}">Partes<em>Meteorologicos</em></a></div>
                </div>
                <div class="col-xs-10 text-right menu-1 main-nav">
                    <span>Insertar </span>
                    <ul>
                        {% if 'principal.add_estacion' in request.user.get_all_permissions %}
                            <li style="cursor: pointer"><a onclick="window.location.replace('/estaciones/adicionar/')">Estaciones</a>
                            </li>
                        {% endif %}
                        {% if 'principal.add_reportevariablemeteorologica' in request.user.get_all_permissions %}
                            <li style="cursor: pointer"><a onclick="window.location.replace('/rvm/adicionar/')">RVM</a></li>
                        {% endif %}
                        {% if 'principal.add_informevariablemeteorologicageneral' in request.user.get_all_permissions %}
                            <li style="cursor: pointer"><a onclick="window.location.replace('/iovmg/adicionar/')">IOVMG</a>
                            </li>
                        {% endif %}
                        {% if 'principal.add_informeoficialvariablemeteorologicapronvincial' in request.user.get_all_permissions %}
                            <li style="cursor: pointer"><a onclick="window.location.replace('/iovmp/adicionar/')">IOVMP</a>
                            </li>
                        {% endif %}
                        {% if 'principal.add_partemeteorologicoprovincial' in request.user.get_all_permissions %}
                            <li style="cursor: pointer"><a onclick="window.location.replace('/pmp/adicionar/')">PMP</a>
                        {% endif %}
                        {% if 'principal.add_partemeteorologicogeneral' in request.user.get_all_permissions %}
                            <li style="cursor: pointer"><a onclick="window.location.replace('/pmg/adicionar/')">PMG</a>
                        {% endif %}
                    </ul>
                </div>
                Bienvenido {{ usuario }}<br>
                <a href="{% url 'cerrar_sesion' %}">Cerrar sesion</a><br>
                <a href="{% url 'index' %}">Ver listado de partes meteorológicos</a><br>
            </div>

        </div>
    </nav>
    <section id="gtco-about" data-section="about" style="padding: 18em 0">
        <div class="row" style="margin-left: 50px">
            <div class="col-md-6">
                <h1>Estaciones</h1>
                <table>
                    <tr>
                        <th>ID</th>
                        <th>Nombre</th>
                    </tr>
                    {% for estacion in estaciones %}
                        <tr>

                            <td><a href="{% url 'estacion_modify_view' estacion.pk %}">{{ estacion.pk }}</a></td>
                            <td><a href="{% url 'estacion_modify_view' estacion.pk %}">{{ estacion.estacion }}</a></td>

                        </tr>
                    {% endfor %}

                </table>
            </div>

        </div>
        <div class="col-md-12">
            <h1>Reportes de variables meteorólogicas</h1>
            <table style="text-align: center">
                <tr>
                    <th>Estación</th>
                    <th>Meteorólogo</th>
                    <th>Fecha y hora</th>
                    <th>Temperatura</th>
                    <th>Humedad</th>
                    <th>Presion</th>
                    <th>DIRR</th>
                    <th>DIRS</th>
                    <th>VELS</th>
                    <th>VELP</th>
                </tr>
                {% for item in rvm %}
                    <tr>
                        <td><a href="{% url 'rvm_modify_view' item.pk %}">{{ item.estacion }}</a></td>
                        <td><a href="{% url 'rvm_modify_view' item.pk %}">{{ item.meteorologo }}</a></td>
                        <td><a href="{% url 'rvm_modify_view' item.pk %}">{{ item.fecha_hora }}</a></td>
                        <td>{{ item.temperatura }}</td>
                        <td>{{ item.humedad }}</td>
                        <td>{{ item.presion }}</td>
                        <td>{{ item.dirr }}</td>
                        <td>{{ item.dirs }}</td>
                        <td>{{ item.vels }}</td>
                        <td>{{ item.velp }}</td>
                    </tr>
                {% endfor %}

            </table>
        </div>

        <div class="col-md-12" style="margin-top: 10px">
            <h1>Informes oficiales de variables meteorólogicas generales</h1>
            <table style="text-align: center">
                <tr>
                    <th>Tecnico</th>
                    <th>Fecha y hora</th>
                    <th>Temperatura</th>
                    <th>Viento</th>
                    <th>Lluvia</th>
                    <th>Humedad</th>
                    <th>Barometro</th>
                </tr>
                {% for item in iovmg %}
                    <tr>
                        <td><a href="{% url 'iovmg_modify_view' item.pk %}">{{ item.tecnico }}</a></td>
                        <td><a href="{% url 'iovmg_modify_view' item.pk %}">{{ item.fecha_hora }}</a></td>
                        <td>{{ item.temperatura }}</td>
                        <td>{{ item.viento }}</td>
                        <td>{{ item.lluvia }}</td>
                        <td>{{ item.humedad }}</td>
                        <td>{{ item.barometro }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>

        <div class="col-md-12" style="margin-top: 10px">
            <h1>Informes oficiales de variables meteorólogicas provinciales</h1>
            <table style="text-align: center">
                <tr>
                    <th>Provincia</th>
                    <th>Estación</th>
                    <th>Fecha y hora</th>
                    <th>Viento</th>
                    <th>Lluvia</th>
                    <th>Temperatura</th>
                    <th>Humedad</th>
                    <th>Barometro</th>
                </tr>
                {% for item in iovmp %}
                    <tr>
                        <td><a href="{% url 'iovmp_modify_view' item.pk %}">{{ item.get_provincia_display }}</a></td>
                        <td><a href="{% url 'iovmp_modify_view' item.pk %}">{{ item.estacion }}</a></td>
                        <td><a href="{% url 'iovmp_modify_view' item.pk %}">{{ item.fecha_hora }}</a></td>
                        <td>{{ item.viento }}</td>
                        <td>{{ item.lluvia }}</td>
                        <td>{{ item.temperatura }}</td>
                        <td>{{ item.humedad }}</td>
                        <td>{{ item.barometro }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        <div class="col-md-12" style="margin-top: 10px">
            <h1>Partes meteorológicos provinciales</h1>
            <table style="text-align: center">
                <tr>
                    <th>Provincia</th>
                    <th>Meteorólogo</th>
                    <th>fecha y hora</th>
                    <th>Temperatura</th>
                    <th>Viento</th>
                    <th>LLuvia</th>
                </tr>
                {% for item in pmp %}
                    <tr>
                        <td><a href="{% url 'pmp_modify_view' item.pk %}">{{ item.get_provincia_display }}</a></td>
                        <td><a href="{% url 'pmp_modify_view' item.pk %}">{{ item.meteorologo }}</a></td>
                        <td><a href="{% url 'pmp_modify_view' item.pk %}">{{ item.fecha_hora }}</a></td>
                        <td>{{ item.temperatura }}</td>
                        <td>{{ item.viento }}</td>
                        <td>{{ item.lluvia }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        <div class="col-md-12" style="margin-top: 10px">
            <h1>Partes meteorológicos generales</h1>
            <table style="text-align: center">
                <tr>
                    <th>Tecnico</th>
                    <th>Fecha y hora</th>
                    <th>Temperatura</th>
                    <th>Viento</th>
                    <th>LLuvia</th>
                </tr>
                {% for item in pmg %}
                    <tr>
                        <td><a href="{% url 'pmg_modify_view' item.pk %}">{{ item.tecnico }}</a></td>
                        <td><a href="{% url 'pmg_modify_view' item.pk %}">{{ item.fecha_hora }}</a></td>
                        <td>{{ item.temperatura }}</td>
                        <td>{{ item.viento }}</td>
                        <td>{{ item.lluvia }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </section>



{% endblock %}

templates/base.html
<!DOCTYPE HTML>
{% load static %}
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Partes meteorológicos generales - Login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Partes meteorológicos generales"/>
    <meta name="keywords" content="parte, meteorologia, parte meteorologico"/>
    <meta name="author" content="MouS"/>

    <!-- Facebook and Twitter integration -->
    <meta property="og:title" content=""/>
    <meta property="og:image" content=""/>
    <meta property="og:url" content=""/>
    <meta property="og:site_name" content=""/>
    <meta property="og:description" content=""/>
    <meta name="twitter:title" content=""/>
    <meta name="twitter:image" content=""/>
    <meta name="twitter:url" content=""/>
    <meta name="twitter:card" content=""/>

    <!-- <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400, 900" rel="stylesheet"> -->

    <!-- Animate.css -->
    <link rel="stylesheet" href="{% static 'principal/css/animate.css' %}">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="{% static 'principal/css/icomoon.css' %}">
    <!-- Themify Icons-->
    <link rel="stylesheet" href="{% static 'principal/css/themify-icons.css' %}">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="{% static 'principal/css/bootstrap.css' %}">
    <!-- Magnific Popup -->
    <link rel="stylesheet" href="{% static 'principal/css/magnific-popup.css' %}">
    <!-- Owl Carousel  -->
    <link rel="stylesheet" href="{% static 'principal/css/owl.theme.default.min.css' %}">
    <!-- Theme style  -->
    <link rel="stylesheet" href="{% static 'principal/css/style.css' %}">

    <!-- Modernizr JS -->
    <script src="{% static 'principal/js/modernizr-2.6.2.min.js' %}"></script>
    <!-- FOR IE9 below -->
    <!--[if lt IE 9]>
	<script src="{% static 'principal/js/respond.min.js' %}"></script>
	<![endif]-->
    {% block extra-estilos %}
    {% endblock %}
</head>
<body>

<div class="gtco-loader"></div>

<div id="page">

    {% block contenido %}
    {% endblock %}

    <footer id="gtco-footer" role="contentinfo">
        <div class="container">

            <div class="row copyright">
                <div class="col-md-12">
                    <p class="pull-left">
                        <small class="block">&copy; 2022 Gestion de partes meteorológicos.</small>
                        <small class="block">Implementado por MouS </small>
                    </p>
                </div>
            </div>

        </div>
    </footer>
</div>

<div class="gototop js-top">
    <a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
</div>

<!-- jQuery -->
<script src="{% static 'principal/js/jquery.min.js' %}"></script>
<!-- jQuery Easing -->
<script src="{% static 'principal/js/jquery.easing.1.3.js' %}"></script>
<!-- Bootstrap -->
<script src="{% static 'principal/js/bootstrap.min.js' %}"></script>
<!-- Waypoints -->
<script src="{% static 'principal/js/jquery.waypoints.min.js' %}"></script>
<!-- Stellar -->
<script src="{% static 'principal/js/jquery.stellar.min.js' %}"></script>
<!-- Magnific Popup -->
<script src="{% static 'principal/js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'principal/js/magnific-popup-options.js' %}"></script>
<!-- Main -->
<script src="{% static 'principal/js/main.js' %}"></script>
{% block extra-scripts %}
{% endblock %}
</body>
</html>

templates/index.html
<!DOCTYPE HTML>
{% load static %}
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Partes meteorológicos generales</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Partes meteorológicos generales"/>
    <meta name="keywords" content="parte, meteorologia, parte meteorologico"/>
    <meta name="author" content="MouS"/>

    <!-- Facebook and Twitter integration -->
    <meta property="og:title" content=""/>
    <meta property="og:image" content=""/>
    <meta property="og:url" content=""/>
    <meta property="og:site_name" content=""/>
    <meta property="og:description" content=""/>
    <meta name="twitter:title" content=""/>
    <meta name="twitter:image" content=""/>
    <meta name="twitter:url" content=""/>
    <meta name="twitter:card" content=""/>

    <!-- <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400, 900" rel="stylesheet"> -->

    <!-- Animate.css -->
    <link rel="stylesheet" href="{% static 'principal/css/animate.css' %}">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="{% static 'principal/css/icomoon.css' %}">
    <!-- Themify Icons-->
    <link rel="stylesheet" href="{% static 'principal/css/themify-icons.css' %}">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="{% static 'principal/css/bootstrap.css' %}">
    <!-- Magnific Popup -->
    <link rel="stylesheet" href="{% static 'principal/css/magnific-popup.css' %}">
    <!-- Owl Carousel  -->
    <link rel="stylesheet" href="{% static 'principal/css/owl.theme.default.min.css' %}">
    <!-- Theme style  -->
    <link rel="stylesheet" href="{% static 'principal/css/style.css' %}">

    <!-- Modernizr JS -->
    <script src="{% static 'principal/js/modernizr-2.6.2.min.js' %}"></script>
    <!-- FOR IE9 below -->
    <!--[if lt IE 9]>
	<script src="{% static 'principal/js/respond.min.js' %}"></script>
	<![endif]-->

</head>
<body>

<div class="gtco-loader"></div>

<div id="page">
    <nav class="gtco-nav" role="navigation">
        <div class="container">
            <div class="row">
                <div class="col-sm-2 col-xs-12">
                    <div id="gtco-logo"><a href="{% url 'index' %}">Partes Meteorológicos<em> Generales</em></a></div>
                </div>
            </div>
        </div>
    </nav>

    <section id="gtco-about" data-section="about">
        <div class="container">
            <div class="row row-pb-md">
                <div class="col-md-8 col-md-offset-2 heading animate-box" data-animate-effect="fadeIn">
                    <h1>Listado de partes meteorológicos</h1>
                    <p class="sub">Abajo se divulgan los partes meteorológicos generales con carácter histórico</p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 col-md-pull-1 animate-box" data-animate-effect="fadeInLeft">
                    <div class="img-shadow">
                        <img src="{% static 'principal/images/meteorologia.jpg' %}" style="max-width: 500px" class="img-responsive"
                             alt="cosas de meteorologia">
                    </div>
                </div>
                <div class="col-md-6 animate-box" data-animate-effect="fadeInLeft">
                        {% for item in pmg %}
                            •<a class="read-more" style="cursor: pointer" id="parte{{ item.pk }}">{{ item.fecha_hora }}
                            - {{ item.tecnico }}</a>

                            <table class="table" style="display: none" id="tabla{{ item.pk }}">
                                <tr>
                                    <td>Tecnico</td>
                                    <td>Fecha y hora</td>
                                    <td>Lluvia</td>
                                    <td>Temperatura</td>
                                    <td>Viento</td>
                                </tr>
                                <tr style="text-align: center">
                                    <td>{{ item.tecnico }}</td>
                                    <td>{{ item.fecha_hora }}</td>
                                    <td>{{ item.lluvia }}</td>
                                    <td>{{ item.temperatura }}</td>
                                    <td>{{ item.viento }}</td>
                                </tr>
                            </table>
                            <br>
                        {% endfor %}
                </div>
            </div>
        </div>
    </section>

    <footer id="gtco-footer" role="contentinfo">
        <div class="container">

            <div class="row copyright">
                <div class="col-md-12">
                    <p class="pull-left">
                        <small class="block">&copy; 2022 Gestion de partes meteorológicos.</small>
                        <small class="block">Implementado por MouS </small>
                    </p>
                </div>
            </div>

        </div>
    </footer>
</div>

<div class="gototop js-top">
    <a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
</div>

<!-- jQuery -->
<script src="{% static 'principal/js/jquery.min.js' %}"></script>
<!-- jQuery Easing -->
<script src="{% static 'principal/js/jquery.easing.1.3.js' %}"></script>
<!-- Bootstrap -->
<script src="{% static 'principal/js/bootstrap.min.js' %}"></script>
<!-- Waypoints -->
<script src="{% static 'principal/js/jquery.waypoints.min.js' %}"></script>
<!-- Stellar -->
<script src="{% static 'principal/js/jquery.stellar.min.js' %}"></script>
<!-- Magnific Popup -->
<script src="{% static 'principal/js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'principal/js/magnific-popup-options.js' %}"></script>
<!-- Main -->
<script src="{% static 'principal/js/main.js' %}"></script>
<script>
    {% for item in pmg %}
        $('#parte{{ item.pk }}').click(function () {
            $('#tabla{{ item.pk }}').toggle('slow')
        });
    {% endfor %}
</script>
</body>
</html>

templates/login.html
{% extends "base.html" %}
{% block contenido %}

{% load crispy_forms_tags %}


<!--Login--> 
<div class="container py-5">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ login_form|crispy }}
    <button class="btn btn-primary" type="submit">Login</button>
  </form>
</div>

{% endblock %}